@startuml

class LMS {
    guid: str <<pk>>
    name: str
    url: URLField
    outcome_url: URLField
    client_id : str
    client_secret : str
}

class LTIUser {
    user: User
    lms: LMS
    lms_guid: str
}

class LTICourse {
    lms: LMS
    lms_guid: str
}

class LTIOutcome {
    user: LTIUser
    resource: LTIResource
    sourcedid: str
}

class LTIResource {
    lms: LMS
    lms_guid: str
    course: LTICourse
}

class LTICourseAbstract<<abstract>> {
    lti : LTICourse <<nullable>>
}

class LTIResourceAbstract<<abstract>> {
    lti : LTIResource <<nullable>>
}

class User<<extern>> {
}

LMS *-- LTIUser
LMS *-- LTICourse
LMS *-- LTIResource
LTIOutcome --> LTIResource
LTIUser *-- LTIOutcome
LTIResourceAbstract --> LTIResource
LTICourseAbstract --> LTICourse
User *-- LTIUser

@enduml
